source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'LITEventMachine_Example', :exclusive => true do
  pod "LITEventMachine", :path => "../"
end

target 'LITEventMachine_Tests', :exclusive => true do
  pod "LITEventMachine", :path => "../"

  
end
